### ISSUE TITLE
Linker error with IAR

### ISSUE THREAD

**Issue by MartinDetech** [MetaWatchOpenProjects/MetaWatch-Gen2#21]
When I tried to build the project in IAR Embedded Workbench IDE for MSP430 Version 5.40.7 I get the following two linker errors:

Error[e46]: Undefined external "SetFirstContact" referred in Wrapper ( E:\MT project\P00155_EU_PROJECT\MetaWatch_firmware\MetaWatchVersion3160\Stack\Api\IAR\Stack.r43 ) 

Error[e46]: Undefined external "ClearFirstContact" referred in Wrapper ( E:\MT project\P00155_EU_PROJECT\MetaWatch_firmware\MetaWatchVersion3160\Stack\Api\IAR\Stack.r43 ) 

I used this versions
(https://github.com/MetaWatchOpenProjects/MetaWatch-WDS11x/commit/e557c7ee246914ab8df50b1c6b3f2181bee71f80)

**Comment by tranxuantrung** [comment]
you can review in project option-->output select library. and optimization select level high.
