### ISSUE TITLE
Request: Reset button combination (if possible)

### ISSUE THREAD

**Issue by bitplane** [MetaWatchOpenProjects/MetaWatch-Gen2#3]
It would be very useful to have a reset button combination, if this is possible, so that we can reset the device when the firmware has crashed.

Failing that, the device should be set to RST mode by default while the firmware is < v1.0

See forum thread for discussion:

http://metawatch.org/forums/thread/63/how-to-reset

**Comment by runCMD0** [comment]
For the next person that wanders here to this old thread desperate to cure a frozen Meta watch screen, when the others linked above failed to work - the following action did work for me ...

Connect your unresponsive Meta to the clip for a few seconds ( I counted to 4 )
remove watch from clip - and then re-insert the clip to make contact with the posts in the back.
attached, wait a few seconds, and remove - then rinse and repeat until the watch resets.

I have 3 Meta watches - after flashing to 1.5.5 - without toggling all my MWM alerts, they all hung.
1 of the watches required me to do the detach-dance mentioned above 10 times, one took only 3 times, and the last - just took 1.  so, ymmv.  Now you have another tool in your toolbelt.
